language: go
dist: xenial
sudo: true
services:
  - docker
matrix:
  include:
    - os: linux
      go: 1.14.x
      cache:
        directories:
          - "/home/travis/.cache/go-build" # GOCACHE
    - os: osx
      go: 1.14.x
      cache:
        directories:
          - "/Users/travis/Library/Caches/go-build" # GOCACHE
    - os: windows
      go: 1.14.x
before_install:
  - mkdir ./bin
  - export PATH=$PATH:$PWD/bin
  # apitest
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -O ./bin/apitest https://github.com/moov-io/api/releases/download/v2020.04.09.1/apitest-linux-amd64; fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget -O ./bin/apitest https://github.com/moov-io/api/releases/download/v2020.04.09.1/apitest-darwin-amd64; fi
  # - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then chmod +x ./bin/apitest; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y make; fi
before_script:
  - GOFILES=$(find . -type f -name '*.go' | grep -v client | grep -v vendor)
  - go mod graph
script:
  - make check
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make docker; fi #  && make test-integration
after_success:
  - bash <(curl -s https://codecov.io/bash)
  # Generate Go clients
  - cd ./api/ && make admin && make client && cd ../
  # Ensure no changes are unstaged in ./admin/ or ./client/ after generating their codeg
  - git diff-index --quiet HEAD -- ./pkg/admin/ ./pkg/client/
  # Build Docker images
  - if [[ "$TRAVIS_OS_NAME" != "linux" ]]; then make docker; fi
after_script:
  # - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then docker-compose logs; fi
  # - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then make clean-integration; fi
before_deploy:
  - make dist
deploy:
  provider: releases
  api_key:
    secure: JaZPNf9Er+wCWwqgfGQowRL8/FZ8FZ4I1CI65ZI16j0HuSxUSdl4ygOeF8SNZ3UMecC8OlRhyuyxIEfoFpxjKvKL7fNyCJCfDGIY/icqmbNoTZitaJwF2QkYQ97U8gtAi1951kcI5A118Ynd/6jKCyYjEhhnlVMJwVuk723A0qWgRFzVekoMWuc+wo4diCrAjVXKvwivJn2CpAYkMlTpQTZgAQm4XbnHtnoB/sR7uDmJpeiOjShfFtYfOTsrqINJND+3bdPTySkPO4MaZ8yB+esdF69URSWOsGhdJf7O0m+494mQjeMdmqyAj0XD7D6NW0253N7oh2ikSa1Cq0xJ1zvUFMnvu3DVlQkEmF+G9pB+C+x0lbxmhO4UelX9wETnohRjZvxqQACZhZrTsh4B+AdGKM1kZkBXpm38aT0U80w7ICczg952is04ZX1YBXXl4m3tWd6MlN3hEdzDaPMj57Rg9v+SyslCLYPQfi0uP1fSc/gjYHogY8UvSLI8R+H7ri71pe/ACoJ/tew6Z6oKyHAigivTBXcGWcDOSWP2DfLBdSrqsKtnDJPiieyINsqzTY1xsHggSTj7bW4PGetg7Yudmf1LB4/A5W5cOTSdhMB4NZh14dbASL/l7eHeZhXGng3XWLX1dBu3h4dsTIm+Mnj/YCbYXFprk4IHzLjADYM=
  file_glob: true
  file:
    - bin/paygate-*
    - bin/paygate.exe
  on:
    repo: moov-io/paygate
    tags: true
    go: 1.14.x
  skip_cleanup: true
after_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make release-push; fi
notifications:
  slack:
    secure: ZJwRHo5yVXMyJ3p4aTM9dQj3NGnrnUoue2bTdTL5W0pHfy+wmqF/ccbTmZrMdNRSaofmLjQ1MS2hnAj3COYZJt+EN3VKG9WCJ8Pcvr6kl6Lmne2f27iGJUTmmQM/ngW4katjTy+BOE3ON5tloa+ixw06jQi/mNLEptj8He49QQDvbTkfP9xrNwMVXqyAEz8AooYHhT3HNc9YpNXnaH703XhHa19R5Kpdolkg5wgVoAGCYJ6PgBBSRfBvXtCqbThVmsean1yZuaXqxjj8WboQ/yiSt8g4cz0+qVsRWa2nvYn3DgP+0cVK4TXJNJ5ruPPpkjIOBye/Zl2ww2qO9OWQxZ1XiFln4sJH6GpZrgT/DsiUJbqcgmNELhDWSY96vEqrEpGAG3uDiTubqO1G3iRGwep6kcIoTPlCouJBRm5mLhdTk/kQazqxkfLn3bamLw+a5rN3UHYeq3s0VAxzDhmziZFBAQCH3OF2+Se7mjyW9w4t7opMF5texXknbluzJR0OVHjjIxj+po4aIpuS6wpQ97jtg3PbQnTE8ogxW8JdTlpG1PVuWh3HwzyMa33qILyx0AFgV9z668O9u0HiF2Xosjx7gBl/bvVJP3XMCZFtc3NHT8Ahz7UOoq7vlI1zumo1KkdPdioJvcfDg121u21/6pohuI1tKzNrVvesppDnN9Y=
