version: '3'
services:
  customers:
    image: moov/customers:latest
    ports:
      - "8087:8087"
      - "9097:9097"
    environment:
      FED_ENDPOINT: 'http://fed:8086'
      # The transit key matches customers.accounts.decryptor.symmetric.keyURI in examples/config.yaml
      TRANSIT_LOCAL_BASE64_KEY: 'base64key://MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI='
      WATCHMAN_ENDPOINT: 'http://watchman:8084'
    depends_on:
      - fed
      - watchman
  fed:
    image: moov/fed:v0.5.0
    ports:
      - "8086:8086"
      - "9096:9096"
    environment:
      FEDACH_DATA_PATH: './data/fed/FedACHdir.txt'
      FEDWIRE_DATA_PATH: './data/fed/fpddir.txt'
  watchman:
    image: moov/watchman:static
    ports:
      - "8084:8084"
      - "9094:9094"
  paygate:
    image: moov/paygate:latest
    ports:
      - "8082:8082"
      - "9092:9092"
    command: ["-config=/conf/config.yaml"]
    volumes:
      - "./examples/:/conf/"
    environment:
      CUSTOMERS_ENDPOINT: 'http://customers:8087'
      # ACH_FILE_MAX_LINES: 20 # upload files when they're a lot smaller than the 10k default
      # ACH_FILE_TRANSFER_INTERVAL: 30s # Merge and Upload files this often
    depends_on:
      - customers
