log_format: json
customers:
  endpoint: "http://localhost:8087"
  accounts:
    decryptor:
      symmetric:
        # INSECURE KEY -- Do not use in production!
        # TODO(adam): "base64key://" after Customers PR is merged
        keyURI: 'MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI='
odfi:
  routing_number: "987654320"
  # gateway:
  #   origin: "CUSTID"
  inbound_path: "inbound/"
  outbound_path: "outbound/"
  return_path: "returned/"
  # allowed_ips: "10.1.0.1,10.2.0.0/16"
  cutoffs:
    # timezone: "America/New_York"
    timezone: "America/Los_Angeles"
    windows:
      - "17:22"
      - "17:24"
      # - "16:20"
  ftp:
    hostname: "localhost:2121"
    username: "admin"
    password: "123456"
    # dial_timeout: 10s
    # disabled_epsv: false
  # sftp:
  #   hostname: "localhost:2222"
  #   username: "demo"
  #   password: "password"
  storage:
    keep_remote_files: false
    local:
      directory: "/opt/moov/storage/"
pipeline:
  # filesystem:
  #   interval: 10m
  #   directory: ./storage/
  stream:
    inmem:
      url: 'mem://paygate'
 # stream:
 #   inmem:
 #     topic: paygate

 #   kafka:
 #     brokers: []
 #     group: ''
 #     topic: ''
