logging:
  format: "plain"
customers:
  endpoint: "http://localhost:8087"
  accounts:
    decryptor:
      symmetric:
        # INSECURE KEY -- Do not use in production!
        keyURI: 'base64key://MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI='
database:
  sqlite:
    path: "paygate.db"
odfi:
  routing_number: "987654320"
  gateway:
    # origin is often an ABA routing number
    origin: "987654320"
    # origin_name is the name of your ODFI
    origin_name: "My Bank"
    # destination can be the ABA routing number of the Federal Reserve bank used
    destination: "071000301"
    # destination_name would be name of Federal Reserve bank used
    destination_name: "FRBATLANTA"
  inbound_path: "./inbound/"
  outbound_path: "./outbound/"
  return_path: "./returned/"
  cutoffs:
    timezone: "America/New_York"
    windows:
      - "16:20" # 4:20pm EST
  inbound:
    interval: "10m"
  transfers:
    balance_entries: true
  ftp:
    hostname: "localhost:2121"
    username: "admin"
    password: "123456"
  # sftp:
  #   hostname: "localhost:2222"
  #   username: "demo"
  #   password: "password"
  storage:
    cleanup_local_directory: true
    keep_remote_files: false
    local:
      directory: "./storage/"
validation:
  micro_deposits:
    source:
      # Example ID's from Moov Customers service
      customerID: "customer"
      accountID: "account"
pipeline:
  output:
    format: "nacha"
  stream:
    inmem:
      url: 'mem://paygate'
  notifications:
    email:
      from: "noreply@moov.io"
      to:
        - "jane@moov.io"
        - "john@moov.io"
      connection_uri: "smtps://test:test@localhost:1025/?insecure_skip_verify=true"
      company_name: "Moov"
