openapi: 3.0.2
info:
  contact:
    url: https://github.com/moov-io/paygate
  description: |
    PayGate is a RESTful API enabling first-party Automated Clearing House ([ACH](https://en.wikipedia.org/wiki/Automated_Clearing_House)) transfers to be created without a deep understanding of a full NACHA file specification. First-party transfers initiate at an Originating Depository Financial Institution (ODFI) and are sent off to other Financial Institutions.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Paygate Admin API
  version: v1
servers:
- description: Local development
  url: http://localhost:9092
tags:
- description: PayGate admin endpoints for checking the running status.
  name: Admin
- description: Tenant objects represent a group of Organizations under one legal entity.
    Typically this is for a vendor who is reselling ACH services to many companies
    and assigns an Organization for each of their clients.
  name: Tenants
- description: Transfer objects create a transaction initiated by an originator to
    a receiver with a defined flow and fund amount. The API allows you to create or
    delete a transfers while the status of the transfer is pending.
  name: Transfers
paths:
  /live:
    get:
      description: Get the status of each depdendency
      operationId: getLivenessProbes
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LivenessProbes'
          description: The status of dependencies
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LivenessProbes'
          description: An error occurred when checking dependencies
      summary: Get Liveness Probes
      tags:
      - Admin
  /version:
    get:
      description: Show the current version of PayGate
      operationId: getVersion
      responses:
        200:
          content:
            text/plain:
              schema:
                example: v0.7.1
                type: string
          description: The current version running
      summary: Get Version
      tags:
      - Admin
  /tenants:
    post:
      description: Create a new Tenant under PayGate
      operationId: createTenant
      parameters:
      - description: Optional requestID allows application developer to trace requests
          through the systems logs
        example: rs4f9915
        explode: false
        in: header
        name: X-Request-ID
        required: false
        schema:
          type: string
        style: simple
      - description: Unique userID set by an auth proxy or client to identify and
          isolate objects.
        explode: false
        in: header
        name: X-User-ID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTenant'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
          description: Created Tenant successfully
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Problem creating Tenant, see error
      summary: Create Tenant
      tags:
      - Tenants
  /transfers/{transferId}/status:
    put:
      description: Updates a Transfer status for the specified userId and transferId
      operationId: updateTransferStatus
      parameters:
      - description: transferID that identifies the Transfer
        explode: false
        in: path
        name: transferId
        required: true
        schema:
          example: e0d54e15
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTransferStatus'
        required: true
      responses:
        200:
          description: Transfer with updated status
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: See error message
      summary: Update Transfer status
      tags:
      - Transfers
components:
  schemas:
    LivenessProbes:
      example:
        customers: good
      properties:
        customers:
          description: Either an error from checking Customers or good as a string.
          example: good
          type: string
    CreateTenant:
      example:
        primaryCustomer: 11ffa67d
        name: My Company
      properties:
        name:
          description: Legal name for this Tenant
          example: My Company
          type: string
        primaryCustomer:
          description: |
            A customerID from the Customers service to use in Transfers with this Tenant. When transfering to or from the Tenant this Customer and Account(s) are used.
            The Customer assigned here should represent the legal entity that manages the Tenant.
          example: 11ffa67d
          type: string
    UpdateTransferStatus:
      example: {}
      properties:
        status:
          $ref: '#/components/schemas/TransferStatus'
    Tenant:
      example:
        primaryCustomer: 11ffa67d
        tenantID: 23cca67d
        name: My Company
      properties:
        tenantID:
          description: tenantID that uniquely identifies this Tenant
          example: 23cca67d
          type: string
        name:
          description: Legal name for this Tenant
          example: My Company
          type: string
        primaryCustomer:
          description: |
            A customerID from the Customers service to use in Transfers with this Tenant. When transfering to or from the Tenant this Customer and Account(s) are used.
            The Customer assigned here should represent the legal entity that manages the Tenant.
          example: 11ffa67d
          type: string
    Error:
      properties:
        error:
          description: An error message describing the problem intended for humans.
          example: Validation error(s) present.
          type: string
      required:
      - error
    TransferStatus:
      description: Defines the state of the Transfer
      enum:
      - canceled
      - failed
      - reviewable
      - pending
      - processed
      type: string
